module.exports = {
  env: {
    browser: true,
    es2021: true,
    node: true,
    jest: true,
    jquery: true,
    'jest/globals': true,
  },
  extends: [
    'airbnb',
    'airbnb-typescript/base',
    'eslint:recommended',
    'plugin:compat/recommended',
    'plugin:react/recommended',
    'plugin:jest/recommended',
    'prettier',
    'prettier/prettier',
    'plugin:import/errors',
    'plugin:import/warnings',
    'plugin:jsx-a11y/recommended',
    'react-app',
    'react-app/jest',
  ],
  // parser: '@babel/eslint-parser',
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaVersion: 12,
    sourceType: 'module',
    requireConfigFile: 'false',
    jsx: true,
  },
  plugins: [
    '@html-eslint',
    'jest',
    'react',
    'jsx-a11y',
    'markdown',
    'react-hooks',
    'import',
    '@typescript-eslint',
  ],
  settings: {
    react: {
      version: 'detect',
    },
    jest: {
      version: 'detect',
    },
  },
  overrides: [
    {
      files: ['*.html'],
      parser: '@html-eslint/parser',
      extends: ['plugin:@html-eslint/recommended'],
    },
  ],
  rules: {
    'react/jsx-filename-extension': '[1, { extensions: [".tsx", ".ts"] }]',
    'import/extensions': 'off',
    'import/prefer-default-export': 'off',
    'prefer-destructuring': 'off',
    'object-shorthand': 'off',
    'react/jsx-props-no-spreading': 'off',
    'arrow-body-style': 'off',
    'no-underscore-dangle': 'off',
    'react/forbid-prop-types': 'off',
  },
};
