import Navbar from 'components/Navbar';
import Section from 'components/Section';
import { pageNotFound } from 'data/pageNotFound';
import { useTranslation } from 'hooks';
import type { NextPage } from 'next';
import Head from 'next/head';

const NotFound: NextPage = () => {
  const { t } = useTranslation();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar t={t} />
      <Section t={t} {...pageNotFound} />
    </div>
  );
};

export default NotFound;
